name: 'ROVALCA S.C. '
favicon: null
layout_spectrum: 0.8023380043450743
typography_spectrum: 0.3302335846237838
title: 'Legal & Finance Strategies'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d2c63'
    - '#aeb1c2'
    - '#861f41'
    - '#797e9c'
  brandStrength: 0.28049697005189955
  lightness: 0.27256559347733855
  saturation: 0.1985764834098518
  rhythmicContrast: 0.15906895697116852
purpose: []
